# https://community.hetzner.com/tutorials/install-and-configure-docker
# https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md
# etc/nginx/conf.d/upstream.conf
# docker inspect to get ip address
# pull latest and run
# docker compose pull  && docker compose up -d
services:
  btree-server:
    container_name: btree-server-beta
    image: hannesoberreiter/btree_server:beta
    # To run knex commands
    # entrypoint: [ "/bin/sh", "-c", "pnpm run prod:knex migrate:latest" ]
    restart: unless-stopped
    user: node
    environment:
      ENVIRONMENT: production
      IS_CHILD: false
    volumes:
      - ./env:/home/node/app/env
      - ./migration:/home/node/app/db/seeds/migration
    ports:
      - '1339:8101'
    logging:
      driver: local
      options:
        max-size: 20m
        max-file: 5

networks:
  default:
    external: true
    name: database-beta_btree-db-network-beta
