FROM node:16.1.0

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Copy Our Files
COPY . .
# Install dependencies
RUN npm install

# Exports
EXPOSE 8101
CMD [ "npm", "run", "nodemon" ]