# https://community.hetzner.com/tutorials/install-and-configure-docker
# https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md
# etc/nginx/conf.d/upstream.conf
# docker inspect to get ip adress
# pull latest and run
# docker compose pull  && docker compose up -d
version: '3.8'
services:
  btree-server:
    container_name: btree-server
    image: hannesoberreiter/btree_server:latest
    # To run knex commands
    # entrypoint: [ "/bin/sh", "-c", "npm run prod:knex migrate:latest" ]
    restart: always
    user: node # connected volume logs must have write access as node user chown -R 1000:1000 logs
    environment:
      ENVIRONMENT: production
      IS_CHILD: false
    volumes:
      - ./env:/home/node/app/env
      - ./logs:/home/node/app/logs
      - ./migration:/home/node/app/db/seeds/migration
    ports:
      - '1338:8101'
    logging:
      driver: local

networks:
  default:
    external: true
    name: database_btree-db-network
