version: '3'
services:
  btree_api_production:
    container_name: btree_api_production
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - 81:8101
