#### REST-Client VSCode Extension

GET http://localhost:8101/api/v1/status HTTP/1.1
content-type: application/json
Origin: http://localhost:8001

#######

GET http://localhost:8101/api/v1/report-violation HTTP/1.1
content-type: application/json
Origin: http://localhost:8001

####### Company

GET http://localhost:8101/api/v1/company/ HTTP/1.1
content-type: application/json
Origin: http://localhost:8001

####### Hives

GET http://localhost:8101/api/v1/hive/ HTTP/1.1
content-type: application/json
Origin: http://localhost:8001

####### Options

GET http://localhost:8101/api/v1/option/checkup_types/ HTTP/1.1
content-type: application/json
Origin: http://localhost:8001