name: test

on:
  pull_request:
    branches: [main, beta]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ci
      NODE_ENV: ci
      DB_DATABASE: ci_test
      DB_USER: root
      DB_PASSWORD: root
      REDIS_HOSTNAME: localhost
      REDIS_USERNAME: default
      REDIS_PORT: 6379

    services:
      mariadb:
        image: mariadb:lts
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: ci_test
        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: pnpm
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Build dist
        run: pnpm run build
      - name: List output files
        run: ls
      - name: Run e2e tests
        run: pnpm run ci:e2e
